### PR TITLE
Testing And CI - CU-1cgtgyq

### PR DESCRIPTION
**Pull request by TheDarkula**

### CODE REVIEW

**Comment by ben-haware** [comment]
In order for the tests to pass we need to either set up a wallet test env or mock the wallet. The tests are failing on calls to melwalletd

**Comment by jaybutera** [comment]
As of now these are only unit tests on the ginkou API to melwalletd. Since these will only change when melwalletd API changes, which is not often, its definitely not a high priority issue. It would be better to disable those tests.

Likely in the future we would eventually want a test environment for the wallet but there's not much of a use case as I see it right now.

**Comment by nullchinchilla** [comment]
I think generally testing GUI apps is extremely tricky, and it's not something I have much experience on. Considering the simplicity of ginkou as it is (most of the interesting business logic is in melwalletd which should have its own tests), perhaps we can hold off on automated testing for now.

**Comment by TheDarkula** [comment]
Task linked: [CU-1cgtgyq Finish Testing For Ginkou](https://app.clickup.com/t/1cgtgyq)

**Comment by ben-haware** [comment]
The simplicity of the app lends itself to simple testing. With jest, testing front ends is pretty straight forward. My main difficulty is a lack of familiarity with svelte. 

We should definitely write tests for both systems and run integration testing at some point. However, we can refocus and work on other more crucial parts of the system if we feel comfortable with testing ginkou by hand for now. 

It shouldn't take more than a couple days to write tests including mocking melwalletd output but we'll have to be careful about making changes to melwalletd

**Comment by ben-haware** [comment]
Thoughts?

**Comment by TheDarkula** [comment]
It sounds like doing the mocks would cause us to maintain two codebaseses, which always leads to drift.
I feel like actual integration testing is the best thing to do. CU-1d9pzz4

**Comment by ben-haware** [comment]
I disabled all tests for now

**Review by jaybutera — APPROVED** [review]

**Pull request merged**
